// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWindow():Promise<void>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function SendRequest(arg1:string,arg2:string):Promise<main.Response>;
